#!/bin/bash

if [ $# -lt 1 ]; then
	printf "Need at least 1 argument\n" $#
	exit 1
fi

for arg in "$@"; do
	(rm -rf "build/$arg" && cmake --preset $arg && cmake --build --preset $arg && cp build/test_input/ro_src/test.mesh "build/$arg/") || printf "\nUnknown preset: %s\n" $arg
done
